version: '3.8'
services:
    mollyfish-dev-db:
        image: postgres:latest
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: P05t9R355
            POSTGRES_DB: dev_mollyfish
        networks:
            - development
    mollyfish-test-db:
        image: postgres:latest
        ports:
            - 9879:9876
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test_mollyfish
        networks:
            - testing
networks:
    development:
    testing:
